INSERT INTO FLIGHT (ID,DEPARTURE_DATE,DESTINATION,ORIGIN,  FLIGHT_NUMBER, MAATSCHAPIJ, OMSCHRIJVING , RETURN_DATE)
VALUES(1, '2059-03-14', 'Hell', 'Earth', 86321, 'Satans Airlines','Highway to hell' , '2059-05-28');

INSERT INTO FLIGHT (ID,DEPARTURE_DATE,DESTINATION, ORIGIN, FLIGHT_NUMBER, MAATSCHAPIJ, OMSCHRIJVING , RETURN_DATE)
VALUES(2, '2032-09-20', 'Heaven', 'Unknown plain', 86322, 'Gods Airlines', 'Highway to heaven', '2034-10-26');

INSERT INTO AIRPORT (ID, NAME, CITY, COUNTRY)
