INSERT INTO FLIGHT (ID,DEPARTURE_DATE,DESTINATION,ORIGIN,  FLIGHT_NUMBER, MAATSCHAPIJ, OMSCHRIJVING , RETURN_DATE)
VALUES(1, '2059-03-14', 'Mars', 'Earth', 86321, 'Worst Airlines','Travel route 1' , '2059-05-28');

INSERT INTO FLIGHT (ID,DEPARTURE_DATE,DESTINATION, ORIGIN, FLIGHT_NUMBER, MAATSCHAPIJ, OMSCHRIJVING , RETURN_DATE)
VALUES(2, '2032-09-20', 'Pluto', 'Jupiter', 86322, 'Best Airlines', 'Travel route 2', '2034-10-26');

INSERT INTO AIRPORT (ID, CITY, COUNTRY, NAME)
VALUES (1, 'Zaventem', 'Belgium','Airport One');

INSERT INTO AIRPORT (ID, CITY, COUNTRY, NAME)
VALUES (2, 'Brussel', 'Belgium','Airport Two');

INSERT INTO AIRPORT (ID, CITY, COUNTRY, NAME)
VALUES (3, 'Charleroi', 'Belgium','Airport Three');

INSERT INTO AIRPORT_FLIGHTS (AIRPORTS_ID, FLIGHTS_ID)
VALUES (1, 1);

INSERT INTO AIRPORT_FLIGHTS (AIRPORTS_ID, FLIGHTS_ID)
VALUES (1, 2);

INSERT INTO AIRPORT_FLIGHTS (AIRPORTS_ID, FLIGHTS_ID)
VALUES (2, 2);
